# create life table function

#' Create life table
#'
#' Creates life table from a list of transition probability matrices at some initial age
#' and specified cohort size.
#'
#' @param trans_probs
#' list of transition probability matrices; typically generated by \code{\link[tshm]{get_trans_probs}}
#' @param age
#' integer denoting current age
#' @param init_state
#' integer value of 0 or 1, where 0 indicates healthy and 1 indicates disabled
#' @param cohort
#' initial cohort size for lifetable
#'
#' @return
#' dataframe of lifetable generated
#'
#' @export
#'
#' @examples
#'
create_life_table <- function(trans_probs, age, init_state = 0, cohort = 100000) {
  # create first row
  if (init_state == 0) {
    life_table <- data.frame('age' = age,
                             'lx' = cohort,
                             'dx' = cohort*trans_probs[[1]][1, 3],
                             'fx' = cohort*trans_probs[[1]][1, 2],
                             'rx' = 0,
                             'Lx' = cohort,
                             'Fx' = 0,
                             'Dx1' = cohort*trans_probs[[1]][1, 3],
                             'Dx2' = 0)
  } else {
    life_table <- data.frame('age' = age,
                             'lx' = 0,
                             'dx' = cohort*trans_probs[[1]][2, 3],
                             'fx' = 0,
                             'rx' = cohort*trans_probs[[1]][2, 1],
                             'Lx' = cohort,
                             'Fx' = cohort,
                             'Dx1' = 0,
                             'Dx2' = cohort*trans_probs[[1]][2, 3])
  }
  for (i in 2:(110-age+1)) {
    # we need to account for all transitions at each age using the transition probailities
    life_table[i, 'age'] <- age + i - 1
    life_table[i, 'lx'] <- life_table[i-1, 'lx'] - life_table[i-1, 'Dx1'] - life_table[i-1, 'fx'] + life_table[i-1, 'rx']
    life_table[i, 'Fx'] <- life_table[i-1, 'Fx'] + life_table[i-1, 'fx'] - life_table[i-1, 'rx'] - life_table[i-1, 'Dx2']
    life_table[i, 'Lx'] <- life_table[i, 'lx'] + life_table[i, 'Fx']
    life_table[i, 'fx'] <- life_table[i, 'lx']*trans_probs[[i]][1, 2]
    life_table[i, 'rx'] <- life_table[i, 'Fx']*trans_probs[[i]][2, 1]
    life_table[i, 'Dx1'] <- life_table[i, 'lx']*trans_probs[[i]][1, 3]
    life_table[i, 'Dx2'] <- life_table[i, 'Fx']*trans_probs[[i]][2, 3]
    life_table[i, 'dx'] <- life_table[i, 'Dx1'] + life_table[i, 'Dx2']
  }

  return(life_table)
}
