# statistics functions

#' Average future lifetime
#'
#' Calculates the average future life time and its standard deviation
#' given initial state and age of an individual by simulating life time paths.
#' Function needs to be provided either a list of transition probability matrices,
#' or a simulated lifetime path from \code{\link[tshm]{simulate_path}}. If both are provided,
#' then the function will use the simulated path provided.
#' NOTE: USE \code{\link[tshm]{aflF}} for frailty model.
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#'
#' @param init_state
#' 0 for healthy, 1 for disabled
#'
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from
#' \code{\link[tshm]{get_trans_probs}}.
#'
#' @param simulated_path
#' a matrix of lifetime paths simulations, generated by \code{\link[tshm]{simulate_path}}.
#'
#' @return
#' numeric output for average and standard deviation of future lifetime
#'
#' @export
#'
#' @examples
afl <- function(init_age, init_state, trans_probs = NULL, simulated_path = NULL) {
  # screening for errors
  if (init_state != 0 & init_state != 1) {
    return('Please enter a valid initial state: 0 for healthy, 1 for disabled.')
  }

  if (init_age<65 | init_age>110) {
    return('Error: init_age outside bounds of allowable age values')
  }

  if (is.null(trans_probs) & is.null(simulated_path)) {
    return('Either transition probability matrices or simulated path must be provided.')
  }

  if (!is.null(simulated_path) & !is.null(trans_probs)) {
    # simulate path
    SP <- simulated_path
  } else if (is.null(trans_probs)) {
    SP <- simulated_path
  } else {
    SP <- tshm::simulate_path(init_age, init_state, trans_probs)
  }
  # count time at death
  future_lifetimes <- rep(0, nrow(SP))
  for (i in 1:nrow(SP)) {
    row_val = SP[i, ]
    future_lifetimes[i] <- which(row_val == -1)[1]-1-0.5 # assume transition happens mid year
  }
  return(c('mean' = mean(future_lifetimes), 's.dev' = sd(future_lifetimes)))
}



#' Average future lifetime (Frailty Model)
#'
#' Performs the same function as the \code{\link[tshm]{afl}}, but simulates a number of
#' unique latent factor paths to make probabilities stochastic.
#' NOTE: USE \code{\link[tshm]{afl}} for static and trend models.
#'
#' @param init_age
#' integer between 65 and 110 indicating initial age of individual
#'
#' @param init_state
#' 0 for healthy, 1 for disabled
#'
#' @param female
#' 0 for male, 1 for female
#'
#' @param year
#' integer indicating current year
#'
#' @param param_file
#' string name of file containing all the parameters of the model
#'
#' @param n
#' integer denoting number of unique latent factor simulations
#'
#'
#' @return
#' numeric output for expected future lifetime and standard deviation of future lifetime
#'
#' @export
#'
#' @examples
aflF <- function(init_age, init_state, female, year, param_file, n = 1000) {
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    return('Error: Please enter an age between 65 and 110.')
  }

  if (init_state != 0 & init_state != 1) {
    return('Error: Please input 0 (healthy) or 1 (disabled) for initial state.')
  }

  if (female != 0 & female != 1) {
    return('Error: Please input 0 or 1 to indicate female.')
  }

  if (n != as.integer(n)) {
    return('Error: Please input an integer for n.')
  }

  future_lifetimes <- rep(0, n*10000)
  for (x in 1:n) {
    # simulate new frailty path for each iteration
    TP <- tshm::get_trans_probs('F', param_file, init_age, female, year)
    SP <- tshm::simulate_path(init_age, init_state, TP)
    for (i in 1:nrow(SP)) {
      row_val <- SP[i, ]
      future_lifetimes[(x-1)*10000+i] <- which(row_val == -1)[1]-1-0.5
    }
  }
  return(c('mean' = mean(future_lifetimes), 's.dev' = sd(future_lifetimes)))
}


#' Healthy Future lifetime
#'
#' Calculates the expected future lifetime spent and its standard deviation
#' in the healthy state. Function uses either transition probability matrices, or
#' a simulated lifetime paths. If both are provided, it will use the simulated lifetime
#' provided.
#' NOTE: USE \code{\link[tshm]{hflF}} FOR FRAILTY MODEL.
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#'
#' @param init_state
#' 0 for healthy, 1 for disabled
#'
#' @param trans_probs
#' list of transition probability matrices; ideally generated from
#' \code{\link[tshm]{get_trans_probs}}.
#'
#' @param simulated_path
#' a matrix of lifetime paths simulations, generated by \code{\link[tshm]{simulate_path}}.
#'
#' @return
#' Numeric output of expected time and standard deviation of time spent in healthy state.
#'
#' @export
#'
#' @examples
hfl <- function(init_age, init_state, trans_probs = NULL, simulated_path = NULL) {
  # screening for errors
  if (init_state != 0 & init_state != 1) {
    return('Please enter a valid initial state: 0 for healthy, 1 for disabled.')
  }

  if (init_age<65 | init_age>110) {
    return('Error: init_age outside bounds of allowable age values')
  }

  if (is.null(trans_probs) & is.null(simulated_path)) {
    return('Either transition probability matrices or simulated path must be provided.')
  }

  # generate simulation path, or just take it from input
  if (!is.null(simulated_path) & !is.null(trans_probs)) {
    SP <- simulated_path
  } else if (is.null(trans_probs)) {
    SP <- simulated_path
  } else {
    # simulate path
    SP <- tshm::simulate_path(init_age, init_state, trans_probs)
  }
  healthy_lifetimes <- rep(0, nrow(SP))
  for (i in 1:nrow(SP)) {
    row_val <- SP[i,]
    if (init_state == 0) {
      healthy_lifetimes[i] <- sum(row_val == 0) - 0.5 # transition happens in middle of period
    } else {
      healthy_lifetimes[i] <- sum(row_val == 0)
    }
  }
  return(c('mean' = mean(healthy_lifetimes), 's_dev' = sd(healthy_lifetimes)))
}

#' Heatlhy Future Lifetime (Frailty Model)
#'
#' Performs the same function as \code{\link[tshm]{hfl}}, but simulates unique latent factor
#' paths in the process.
#' NOTE: USE \code{\link[tshm]{hfl}} for static and trend models.
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#'
#' @param init_state
#' 0 for healthy, 1 for disabled
#'
#' @param female
#' 0 for male, 1 for female
#'
#' @param year
#' integer denoting current year
#'
#' @param param_file
#' string for file path containing parameters of cox regression model
#'
#' @param n
#' integer denoting number of simulations
#'
#' @return
#' Numeric output denoting the average time spent in healthy state and its
#' standard deviation.
#'
#' @export
#'
#' @examples
hflF <- function(init_age, init_state, female, year, param_file, n = 1000) {
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    return('Error: Please enter an age between 65 and 110.')
  }

  if (init_state != 0 & init_state != 1) {
    return('Error: Please input 0 (healthy) or 1 (disabled) for initial state.')
  }

  if (female != 0 & female != 1) {
    return('Error: Please input 0 or 1 to indicate female.')
  }

  if (n != as.integer(n)) {
    return('Error: Please input an integer for n.')
  }

  healthy_lifetimes <- rep(0, n*10000)
  for (x in 1:n) {
    TP <- tshm::get_trans_probs('F', param_file, init_age, female, year)
    SP <- tshm::simulate_path(init_age, init_state, TP)
    for (i in 1:nrow(SP)) {
      row_val <- SP[i,]
      if (init_state == 0) {
        healthy_lifetimes[(x-1)*10000+i] <- sum(row_val == 0) - 0.5
      } else {
        healthy_lifetimes[(x-1)*10000+i] <- sum(row_val == 0)
      }
    }
  }
  return(c('mean' = mean(healthy_lifetimes), 's_dev' = sd(healthy_lifetimes)))
}



#' Average future lifetime in disabled state
#'
#' Calculates the average future lifetime spent in disabled state and the standard
#' deviation by simulating life time paths given a list of transition probability
#' matrices.
#' NOTE: THIS FUNCTION SHOULD ONLY BE USED WITH STATIC AND TREND MODELS. USE
#' \code{\link[tshm]{afldF}} FOR FRAILTY MODEL.
#'
#' @param init_age
#' integer between 65 and 110 denoting age of individual
#'
#' @param init_state
#' 0 for healthy, 1 for disabled
#'
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from
#' \code{\link[tshm]{get_trans_probs}}.
#'
#' @param simulated_path
#' a matrix of lifetime paths simulations, generated by \code{\link[tshm]{simulate_path}}.
#'
#' @return
#' numeric output for average future lifetime in disabled state and its standard
#' deviation.
#'
#' @export
#'
#' @examples
afld <- function(init_age, init_state, trans_probs = NULL, simulated_path = NULL) {
  # screening for errors
  if (init_state != 0 & init_state != 1) {
    return('Please enter a valid initial state: 0 for healthy, 1 for disabled.')
  }

  if (init_age<65 | init_age>110) {
    return('Error: init_age outside bounds of allowable age values')
  }

  if (is.null(trans_probs) & is.null(simulated_path)) {
    return('Either transition probability matrices or simulated path must be provided.')
  }


  # simulate path and count disabled time
  if (!is.null(simulated_path) & !is.null(trans_probs)) {
    SP <- simulated_path
  } else if (is.null(trans_probs)) {
    SP <- simulated_path
  } else {
    # simulate path
    SP <- tshm::simulate_path(init_age, init_state, trans_probs)
  }

  disabled_lifetime <- rep(0, nrow(SP))
  for (i in 1:nrow(SP)) {
    row_val <- SP[i, ]
    if (init_state == 1) {
      disabled_lifetime[i] <- sum(row_val == 1) - 0.5 # transition happens mid year
    } else {
      disabled_lifetime[i] <- sum(row_val == 1)
    }
  }
  return(c('mean' = mean(disabled_lifetime), 's_dev' = sd(disabled_lifetime)))
}


#' Average future lifetime in disabled state (frailty model)
#'
#' Performs the same function as \code{\link[tshm]{afld}}, but it requires inputs
#' to simulate latent factor in the frailty model. This allows it to simulate the
#' the randomness from the frailty factor into the calculation as well.
#' NOTE: THIS FUNCTION SHOULD ONLY BE USED WITH THE FRAILTY MODEL. USE \code{\link[tshm]{afld}}
#' FOR STATIC AND TREND MODEL.
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#' @param init_state
#' 0 for healthy and 1 for disabled
#' @param female
#' 0 for non female, 1 for female
#' @param year
#' integer for current year
#' @param param_file
#' string for file path containing parameters of cox regression model
#' @param n
#' integer representing number of unique latent factors to simulate
#'
#' @return
#' numeric output for average time spent and standard deviation of time in disabled state
#'
#' @export
#'
#' @examples
afldF <- function(init_age, init_state, female, year, param_file, n = 1000) {
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    return('Error: Please enter an age between 65 and 110.')
  }

  if (init_state != 0 & init_state != 1) {
    return('Error: Please input 0 (healthy) or 1 (disabled) for initial state.')
  }

  if (female != 0 & female != 1) {
    return('Error: Please input 0 or 1 to indicate female.')
  }

  if (n != as.integer(n)) {
    return('Error: Please input an integer for n.')
  }

  disabled_lifetime <- rep(0, n*10000)
  # simulate n unique latent factors
  for (x in 1:n) {
    TP <- tshm::get_trans_probs('F', 'US_params_new.xlsx', init_age, female, year)
    SP <- tshm::simulate_path(init_age, init_state, TP)
    for (i in 1:nrow(SP)) {
      row_val <- SP[i,]
      if (init_state == 1) {
        disabled_lifetime[(x-1)*10000+i] <- sum(row_val == 1) - 0.5
      } else {
        disabled_lifetime[(x-1)*10000+i] <- sum(row_val == 1)
      }
    }
  }
  return(c('mean' = mean(disabled_lifetime), 's_dev' = sd(disabled_lifetime)))
}


#' Time until onset of disability (conditional on being disabled)
#'
#' Uses simulation to produce an average time until a healthy individual becomes disabled
#' during their life time. Note that this is conditional on the individual becoming disabled,
#' so it doesn't factor in life simulations where the indiviudal is always healthy.
#' NOTE: USE \code{\link[tshm]{time_to_disabledF}} for frailty model.
#'
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#'
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from
#' \code{\link[tshm]{get_trans_probs}}.
#'
#' @return
#' numeric denoting the average time until individual becomes disabled and its
#' standard deviation.
#'
#' @export
#'
#' @examples
time_to_disabled <- function(init_age, trans_probs) {
  # screening for errors
  if (init_age<65 | init_age>110) {
    return('Error: init_age outside bounds of allowable age values')
  }

  # create a simulation
  simulated_path <- tshm::simulate_path(init_age, 0, trans_probs)

  first_time <- rep(0, nrow(simulated_path))
  for (i in 1:nrow(simulated_path)) {
    row_val <-simulated_path[i, ]
    if (1 %in% row_val) {
      first_time[i] <- which(row_val == 1)[1]-1-0.5
    }
  }
  first_time <- first_time[first_time != 0]
  return(c('mean' = mean(first_time), 'sd' = sd(first_time)))
}



#' Time until onset of disability (Frailty model)
#'
#' Function serves the same purpose as \code{\link[tshm]{time_to_disabled}}, but it is for
#' the frailty model.
#'
#' @param init_age
#' integer between 65 and 110
#'
#' @param female
#' 0 for male, 1 for female
#'
#' @param year
#' integer denoting current year
#'
#' @param param_file
#' string for file path containing parameters of cox regression model
#'
#' @param n
#' integer denoting number of simulations to make
#'
#' @return
#' numeric denoting the average time until individual becomes disabled, and its
#' standard deviation.
#'
#' @export
#'
#' @examples
time_to_disabledF <- function(init_age, female, year, param_file, n = 1000) {
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    return('Error: Please enter an age between 65 and 110.')
  }

  if (female != 0 & female != 1) {
    return('Error: Please input 0 or 1 to indicate female.')
  }

  if (n != as.integer(n)) {
    return('Error: Please input an integer for n.')
  }

  # create n unique latent factor paths
  first_time <- rep(0, n*10000)
  for (x in 1:n) {
    TP <- tshm::get_trans_probs('F', param_file, init_age, female, year)
    SP <- tshm::simulate_path(init_age, 0, TP)
    for (i in nrow(SP)) {
      row_val <- SP[i,]
      if (1 %in% row_val) {
        first_time[(x-1)*10000+i] <- which(row_val == 1)[1]-1-0.5
      }
    }
  }
  first_time <- first_time[first_time != 0]
  return(c('mean' = mean(first_time), 's_dev' = sd(first_time)))
}









