#' Calculate transition probability matrices
#'
#' Creates a list of transition probability matrices starting from initial age to
#' max age of 110 for 3 state model or 5 state model
#'
#' @param n_states
#' take values 3 or 5, use 3 for 3-state model, and 5 for 5-state model
#' @param model_type
#' string that selects model type; S for Static, T for Trend and F for Frailty
#' @param param_file
#' string for file path of parameter file OR a tibble/dataframe of parameters
#' @param init_age
#' integer denoting age of policy holder
#' @param female
#' takes values 1 or 0, where 1 indicates policyholder is female
#' @param year
#' integer denoting current year
#' @param wave_index
#' the wave index = (interview year - 1998)/2 + 1
#' @param latent
#' initial value of latent factor, normally take the value 0
#'
#' @return
#' list of transition probability matrices
#'
#' @export
#' @import expm
#' @examples trans_probs=get_trans_probs(n_states=5, model_type='F', 
#' param_file=US_HRS_5, init_age=65, female=0, year = 2012, wave_index = 8, 
#' latent = 0)
#'
get_trans_probs <- function(n_states, model_type, param_file, init_age, female, year = 2012, wave_index = 8, latent = 0) {

  if (n_states == 5) {
    if (year != 2012) {
      wave_index = (year - 1998) / 2 + 1
    }
    else if (wave_index != 8) {
      year = 2 * (wave_index - 1) + 1998
    }
  }

  if (n_states == 3) {
    return(health3_get_trans_probs(model_type, param_file, init_age, female, year))
  }

  if (n_states == 5) {
    return(health5_get_trans_probs(model_type, param_file, init_age, female, wave_index, latent))
  }

  stop('invalid n_states')
}


#' Create life table
#'
#' Creates life table from a list of transition probability matrices at some initial age
#' and specified cohort size.
#'
#' @param trans_probs
#' list of transition probability matrices; typically generated by \code{get_trans_probs}
#' @param init_age
#' integer denoting current age
#' @param init_state
#' integer value
#' for 3-state model: integer value of 0 or 1, where 0 for healthy state, 1 for disabled state
#' for 5-state model: 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param cohort
#' initial cohort size for lifetable
#'
#' @return
#' dataframe of lifetable generated
#'
#' @export
#'
#' @examples trans_probs=get_trans_probs(n_states=5, model_type='F', 
#' param_file=US_HRS_5, init_age=65, female=0, year = 2012, wave_index = 8, 
#' latent = 0)
#' lifetable <- create_life_table(trans_probs, init_age=65, init_state = 0, cohort = 100000)
#'
create_life_table <- function(trans_probs, init_age, init_state = 0, cohort = 100000) {

  if (length(trans_probs[[1]][1,]) == 3) {
    return(health3_create_life_table(trans_probs, init_age, init_state, cohort))
  }

  if (length(trans_probs[[1]][1,]) == 5) {
    return(health5_create_life_table(trans_probs, init_age, init_state, cohort))
  }

  stop('invalid dimensions: trans_probs')
}


#' Simulate life table for frailty model
#'
#' Simulate life table for for 3 state or 5 state frailty model starting from initial age to
#' max age of 110
#'
#' @param n_states
#' take values 3 or 5, use 3 for 3-state model, and 5 for 5-state model
#' @param model_type
#' select F for Frailty model
#' @param param_file
#' string for file path of parameter file OR a tibble/dataframe of parameters
#' @param init_age
#' integer denoting current age
#' @param female
#' takes values 1 or 0, where 1 indicates policyholder is female
#' @param year
#' integer denoting current year
#' @param init_state
#' integer value
#' for 3-state model: integer value of 0 or 1, where 0 for healthy state, 1 for disabled state
#' for 5-state model: 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param wave_index
#' the wave index = (interview year - 1998)/2 + 1
#' @param latent
#' initial value of latent factor, normally take the value 0
#' @param n_sim
#' number of simulations
#' @param cohort
#' number of people at the beginning of the life table
#' @param mean
#' TRUE to return expected life table, FALSE to return all simulated life tables
#'
#' @return
#' list of life tables (default) or expected life table (mean == TRUE)
#'
#' @export
#'
#' @examples lifetable_simulated <- simulate_life_table(n_states=5, model_type='F', 
#' param_file=US_HRS_5, init_age=65, female=0, year = 2012, init_state = 0, 
#' wave_index = 8,latent=0,n_sim=100,cohort=100,mean=FALSE)
#'
simulate_life_table <- function(n_states, model_type, param_file, init_age, female, year = 2012, init_state = 0, wave_index = 8,latent=0,n_sim=100,cohort=100000,mean=FALSE) {

  if (n_states == 3) {
    return(health3_simulate_life_table(init_age, female, year, param_file, init_state, n_sim, cohort, mean))
  }

  if (n_states == 5) {
    return(health5_simulate_life_table(model_type, param_file, female, wave_index,latent,init_age,init_state,n_sim, cohort, mean))
  }

  stop('invalid n_states')
}


#' Simulate cohort life path
#'
#' Simulates the path each life takes in an initial cohort using transition probabilities
#'
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from \code{\link[tshm]{get_trans_probs}}.
#' @param init_age
#' integer between 65 and 110 denoting current age. This has to the be same as the initial
#' age used in the generation of transition probability matrices.
#' @param init_state
#' integer value
#' for 3-state model: integer value of 0 or 1, where 0 for healthy state, 1 for disabled state
#' for 5-state model: 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param cohort
#' integer (default 10000) denoting number of people in the simulation
#'
#' @return
#' a matrix where each row represents a new individual, and the columns represent
#' the individual's movement through each state.
#' for 3-state model: 0 for healthy state, 1 for disabled state, -1 for death state
#' for 5-state model: 0 for H state, 1 for M state, 2 for D state, 3 for MD state, -1 for death state
#' -1 (death) is absorbing, so if an individual enters that state, the rest of the row will be -1.
#'
#' @export
#'
#' @examples trans_probs=get_trans_probs(n_states=5, model_type='F', 
#' param_file=US_HRS_5, init_age=65, female=0, year = 2012, wave_index = 8, 
#' latent = 0)
#' simulated_path <- simulate_health_state_paths(trans_probs, init_age=65, 
#' init_state = 0, cohort = 10000)
simulate_health_state_paths <- function(trans_probs, init_age, init_state = 0, cohort = 10000) {

  if (length(trans_probs[[1]][1,]) == 3) {
    return(health3_simulate_paths(trans_probs, init_age, init_state, cohort))
  }

  if (length(trans_probs[[1]][1,]) == 5) {
    return(health5_simulate_paths(trans_probs, init_age, init_state, cohort))
  }

  stop('invalid dimensions: trans_probs')
}

#' Create Survival Probability Plots
#'
#' Create a plot of survival probabilities to different states.
#'
#' @param init_age
#' integer between 65 and 110 denoting current age. This has to the be same as the initial
#' age used in the generation of transition probability matrices.
#' @param init_state
#' integer value
#' for 3-state model: integer value of 0 or 1, where 0 for healthy state, 1 for disabled state
#' for 5-state model: 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from \code{\link[tshm]{get_trans_probs}}.
#'
#' @return
#' line plot denoting Probability of surviving to each different state
#'
#' @export prob_plots
#'
#' @import tidyr dplyr ggplot2
#'
#' @examples trans_probs=get_trans_probs(n_states=5, model_type='F', 
#' param_file=US_HRS_5, init_age=65, female=0, year = 2012, wave_index = 8, 
#' latent = 0)
#' prob_plots(init_state=0, init_age=65, trans_probs=trans_probs)

prob_plots <- function (init_state, init_age, trans_probs) {

    if (length(trans_probs[[1]][1,]) == 3) {
        return(health3_prob_plots(init_state, init_age, trans_probs))
    }

    if (length(trans_probs[[1]][1,]) == 5) {
        return(health5_prob_plots(init_state, init_age, trans_probs))
    }

    stop('invalid dimensions: trans_probs')
}
