# Functions to create different plots

#' Calculate Survival Probabilities
#'
#' Calculates the probability of surviving to a certain age from an initial state and age
#'
#' @param init_state
#' 0 (for healthy) or 1 (for disabled)
#' @param init_age
#' integer between 65 and 110 denoting age of individual. This has to be the same initial
#' age used in the calculation of transition probability matrices.
#' @param target_age
#' integer between 65 and 110 denoting the target age to survive to.
#' @param trans_probs
#' list of transition probability matrices; this could be generated by \code{health3_get_trans_probs}.
#' @param end_state
#' default NULL to return probability of surviving. Set to 0 for probability ending is healthy, and 1 for disabled.
#'
#' @return
#' numeric denoting probability of surviving to end age in end state
#'
#' @export
#'
#' @examples example
health3_surv_prob <- function(init_state, init_age, target_age, trans_probs, end_state = NULL) {
  # screening for errors
  if (init_state != 0 & init_state != 1) {
    stop('invalid state, use 0 for healthy and 1 for disabled')
  }

  if (!is.null(end_state)) {
    if (end_state != 0 & end_state !=1) {
      stop('invalid end state, use 0 for healthy and 1 for disabled')
    }
  }

  if (init_age >= target_age) {
    stop('initial age is greater than or equal to target age')
  }

  if (init_age<65 | init_age>110) {
    stop('invalid initial age')
  }

  if (as.integer(init_age) != init_age) {
    stop('initial age must be an integer')
  }

  if (target_age < 65 | target_age > 110) {
    stop('invalid target age')
  }

  if (as.integer(target_age) != target_age) {
    stop('target age must be an integer')
  }

  if (length(trans_probs) != 111 - init_age) {
    stop('initial age does not correspond to the number of transition probability matrices')
  }

  # we multiply probability matrices in the trans_probs to get transition rates
  P <- Reduce('%*%', trans_probs[1:(target_age-init_age)])

  # return relevant item from the probability matrix
  if (is.null(end_state)){
    return(P[init_state+1,  1] + P[init_state+1, 2])
  } else {
    return(P[init_state+1, end_state+1])
  }
}


#' Create Survival Probability Plots
#'
#' Create a plot of survival probabilities to alive, health, and disabled states.
#'
#' @param init_state
#' 0 for healthy, 1 for disabled.
#' @param init_age
#' integer between 65 and 110 (inclusive) denoting initial age of individual. This has
#' to be the same as the initial age used for transition probability matrices simulation.
#' @param trans_probs
#' list of transition probability matrices, this could be generated by \code{get_trans_probs}.
#'
#' @return
#' line plot with 3 lines, each denoting survival probability, survival probability to
#' disabled, and survival probability to healthy.
#'
#' @export
#'
#' @import tidyr dplyr ggplot2
#'
#' @examples example
health3_prob_plots <- function(init_state, init_age, trans_probs) {
    age <- alive <- healthy <- disabled <- value <- Type <- NULL
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    stop('invalid age')
  }

  if (as.integer(init_age) != init_age) {
    stop('initial age must be an integer')
  }

  if (init_state != 0 & init_state != 1) {
    stop('invalid state; enter 0 for healthy, 1 for disabled')
  }

  if (length(trans_probs) != 111 - init_age) {
    stop('initial age does not correspond to the number of transition probability matrices')
  }

  # create 3 different probabilities:
  # general alive probability, healthy, and disabled
  alive_probs <- c(1)

  if (init_state == 0) {
    healthy_probs <- c(1)
    disabled_probs <- c(0)
  } else {
    healthy_probs <- c(0)
    disabled_probs <- c(1)
  }
  for (target in (init_age+1):110) {
    alive_probs <- append(alive_probs, health3_surv_prob(init_state, init_age, target, trans_probs))
    healthy_probs <- append(healthy_probs, health3_surv_prob(init_state, init_age, target, trans_probs, end_state = 0))
    disabled_probs <- append(disabled_probs, health3_surv_prob(init_state, init_age, target, trans_probs, end_state = 1))
  }

  # create age axis
  ages <- init_age:110

  # create dataframe for ggplot
  survival_df <- data.frame('age' = ages,
                              'alive' = alive_probs,
                              'healthy' = healthy_probs,
                              'disabled' = disabled_probs)

  updated_df <- survival_df %>%
    dplyr::select(age, alive, healthy, disabled) %>%
    tidyr::gather(key = 'Type', value = 'value', -age)

  surv_plot <- ggplot2::ggplot(updated_df, aes(x = age, y = value)) +
     ggplot2::geom_line(aes(color = Type)) +
     ggplot2::scale_color_manual(labels = c('Alive', 'Disabled', 'Healthy'),
                       values = c('darkolivegreen2', 'lightcoral', 'skyblue1')) +
     ggplot2::ggtitle('Probability of Surviving to each Different State')

  return(surv_plot)
}



