#' Calculate transition probability matrices
#'
#' Creates a list of transition probability matrices starting from initial age to
#' max age of 110 for 3 state model
#'
#' @param model_type
#' string that selects model type; S for Static, T for Trend and F for Frailty
#' @param param_file
#' string for file path of parameter file OR a tibble/dataframe of parameters
#' @param age
#' integer denoting age of policy holder
#' @param gender
#' takes values 1 or 0, where 1 indicates policyholder is female
#' @param year
#' integer denoting current year
#' @param wave_index
#' the wave index
#' @param latent
#' initial value of latent factor, normally take the value 0
#'
#' @return
#' list of transition probability matrices
#'
#' @export get_trans_probs
#'
#'
#' @export get_trans_probs
#' @import expm
#' @examples example
#'
get_trans_probs <- function(n_states, model_type, param_file, age, gender, year = 2012, wave_index = 8, latent = 0) {
  
  if (year != 2012) {
    wave_index = (year - 1998) / 2 + 1
  }
  else if (wave_index != 8) {
    year = 2 * (wave_index - 1) + 1998
  }

  if (n_states == 3) {
    return(health3_get_trans_probs(model_type, param_file, age, gender, year))
  }
 
  if (n_states == 5) {
    return(health5_get_trans_probs(model_type, param_file, age, gender, wave_index, latent))
  }

  stop('invalid n_states')
}


#' Create life table
#'
#' Creates life table from a list of transition probability matrices at some initial age
#' and specified cohort size.
#'
#' @param trans_probs
#' list of transition probability matrices; typically generated by \code{\link[tshm]{get_trans_probs}}
#' @param init_age
#' integer denoting current age
#' @param init_state
#' integer value of 0 or 1, where 0 indicates healthy and 1 indicates disabled
#' @param cohort
#' initial cohort size for lifetable
#'
#' @return
#' dataframe of lifetable generated
#'
#' @export create_life_table
#'
#' @examples example
#'
create_life_table <- function(model_type, trans_probs, init_age, init_state = 0, cohort = 100000) {

  if (length(trans_probs) == 3) {
    return(health3_get_life_table(trans_probs, init_age, init_state, cohort))
  }
 
  if (length(trans_probs) == 5) {
    return(health5_get_life_table(trans_probs, init_age, init_state, cohort))
  }

  stop('invalid dimensions: trans_probs')
}


#' Simulate life table for frailty model
#'
#' Simulate life table for frailty model starting from initial age to
#' max age of 110 for 3 state model
#'
#' @param model_type
#' string that selects model type; S for Static, T for Trend and F for Frailty
#' @param param_file
#' string for file path of parameter file OR a tibble/dataframe of parameters
#' @param age
#' integer denoting age of policy holder
#' @param gender
#' takes values 1 or 0, where 1 indicates policyholder is female
#' @param year
#' integer denoting current year
#' @param wave_index
#' the wave index
#' @param latent
#' initial value of latent factor, normally take the value 0
#' @param n_sim
#' number of simulations
#' @param mean
#' return expected life table
#'
#' @return
#' list of life tables (default) or expected life table (mean == TRUE)
#'
#' @export simulate_life_table
#'
#' @examples example
#'
simulate_life_table <- function(n_states, param_file, age, gender, year = 2012, wave_index = 8, n_sim = 10000, mean = TRUE) {
  
  if (n_states == 3) {
    return(health3_simulate_life_table(param_file, age, gender, year, n_sim, mean))
  }
 
  if (n_states == 5) {
    return(health5_simulate_life_table(param_file, age, gender, wave_index, n_sim, mean))
  }

  stop('invalid n_states')
}


#' Simulate cohort life path
#'
#' Simulates the path each life takes in an initial cohort using transition probabilities
#'
#' @param trans_probs
#' a list of transition probability matrices, preferably generated from \code{\link[tshm]{get_trans_probs}}.
#' @param init_age
#' integer between 65 and 110 denoting current age. This has to the be same as the initial
#' age used in the generation of transition probability matrices.
#' @param init_state
#' 0 for healthy, 1 for disabled
#' @param cohort
#' integer (default 10000) denoting number of people in the simulation
#'
#' @return
#' a matrix where each row represents a new individual, and the columns represent
#' the individual's movement through each state.
#'
#' -1 (death) is absorbing, so if an individual enters that state, the rest of the row will be -1.
#'
#' @export simulate_health_state_paths
#'
#' @examples example
simulate_health_state_paths <- function(trans_probs, init_age, init_state = 0, cohort = 100000) {
  
  if (length(trans_probs) == 3) {
    return(health3_simulate_paths(trans_probs, init_age, init_state, cohort))
  }
 
  if (length(trans_probs) == 5) {
    return(health5_simulate_paths(trans_probs, init_age, init_state, cohortt))
  }

  stop('invalid dimensions: trans_probs')
}