#' Functions to create different plots
#'
#' Create a plot of survival probabilities to H, M, D, MD and Dead states.
#'
#' @param init_state
#' 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param init_age
#' integer between 65 and 110 (inclusive) denoting initial age of individual. This has
#' to be the same as the initial age used for transition probability matrices simulation.
#' @param trans_probs
#' list of transition probability matrices, this could be generated by \code{get_trans_probs}.
#'
#' @return
#' line plot with 5 lines, each denoting probabilities of being in the
#' states H, M, D, MD, Dead respectively.
#'
#' @export
#'
#' @import tidyr dplyr ggplot2
#'
#' @examples example
health5_prob_plots <- function(init_state, init_age, trans_probs) {
    age <- H <- M <- D <- MD <- Dead <- value <- Type <- NULL
  # flagging errors
  if (init_age < 65 | init_age > 110) {
    stop('invalid age')
  }

  if (as.integer(init_age) != init_age) {
    stop('initial age must be an integer')
  }

  if (init_state != 0 & init_state != 1) {
    stop('invalid state; enter 0 for healthy, 1 for disabled')
  }

lifetable=create_life_table(trans_probs, init_age, init_state, cohort = 1)

  # create age axis
  ages <- init_age:111

  # create dataframe for ggplot
  survival_df <- data.frame('age' = ages,
                              'H' = lifetable[,2],
                              'M' = lifetable[,3],
                              'D' = lifetable[,4],
                              'MD'= lifetable[,5],
                              'Dead'= lifetable[,6])

  updated_df <- survival_df %>%
    dplyr::select(age, H, M, D, MD, Dead) %>%
    tidyr::gather(key = 'Type', value = 'value', -age)

  surv_plot <- ggplot2::ggplot(updated_df, aes(x = age, y = value)) +
      ggplot2::geom_line(aes(color = Type)) +
      ggplot2::scale_color_manual(labels = c('D', 'Dead', 'H', 'M', 'MD'),
                       values = c('darkolivegreen2', 'Red', 'skyblue1','blue','yellow')) +
      ggplot2::ggtitle('Probability of Surviving to each Different State')
  return(surv_plot)
}



