# create life table function

#' Create life table
#'
#' Creates life table from a list of transition probability matrices at some initial age
#' and specified cohort size.
#'
#' @param trans_probs
#' list of transition probability matrices; typically generated by \code{health3_get_trans_probs}
#' @param init_age
#' integer denoting current age
#' @param init_state
#' integer value of 0 or 1, where 0 indicates healthy and 1 indicates disabled
#' @param cohort
#' initial cohort size for lifetable
#'
#' @return
#' dataframe of lifetable generated
#'
#' @export create_life_table
#'
#' @examples example
#'
health3_create_life_table <- function(trans_probs, init_age, init_state, cohort) {
    # flagging errors
    if (init_age < 65 | init_age > 110) {
      stop('invalid age')
    }

    if (as.integer(init_age) != init_age) {
      stop('initial age must be an integer')
    }

    if (init_state != 0 & init_state != 1) {
      stop('invalid state, enter 0 for healthy, 1 for disabled')
    }

    if (cohort != floor(cohort)) {
      stop('cohort must be integer value')
    }

    if (cohort <= 0) {
      stop('cohort must be positive integer')
    }

    if (length(trans_probs) != 111 - init_age) {
      stop('initial age does not correspond to the number of transition probability matrices')
    }

    # create first row
    if (init_state == 0) {
      life_table <- data.frame('age' = init_age,
                               'lx' = cohort,
                               'dx' = cohort*trans_probs[[1]][1, 3],
                               'fx' = cohort*trans_probs[[1]][1, 2],
                               'rx' = 0,
                               'Lx' = cohort,
                               'Fx' = 0,
                               'Dx1' = cohort*trans_probs[[1]][1, 3],
                               'Dx2' = 0)
    } else {
      life_table <- data.frame('age' = init_age,
                               'lx' = 0,
                               'dx' = cohort*trans_probs[[1]][2, 3],
                               'fx' = 0,
                               'rx' = cohort*trans_probs[[1]][2, 1],
                               'Lx' = cohort,
                               'Fx' = cohort,
                               'Dx1' = 0,
                               'Dx2' = cohort*trans_probs[[1]][2, 3])
    }
    for (i in 2:(110-init_age+1)) {
      # we need to account for all transitions at each age using the transition probailities
      life_table[i, 'age'] <- init_age + i - 1
      life_table[i, 'lx'] <- life_table[i-1, 'lx'] - life_table[i-1, 'Dx1'] - life_table[i-1, 'fx'] + life_table[i-1, 'rx']
      life_table[i, 'Fx'] <- life_table[i-1, 'Fx'] + life_table[i-1, 'fx'] - life_table[i-1, 'rx'] - life_table[i-1, 'Dx2']
      life_table[i, 'Lx'] <- life_table[i, 'lx'] + life_table[i, 'Fx']
      life_table[i, 'fx'] <- life_table[i, 'lx']*trans_probs[[i]][1, 2]
      life_table[i, 'rx'] <- life_table[i, 'Fx']*trans_probs[[i]][2, 1]
      life_table[i, 'Dx1'] <- life_table[i, 'lx']*trans_probs[[i]][1, 3]
      life_table[i, 'Dx2'] <- life_table[i, 'Fx']*trans_probs[[i]][2, 3]
      life_table[i, 'dx'] <- life_table[i, 'Dx1'] + life_table[i, 'Dx2']
    }

    return(life_table)
}

#' Create life table (frailty model)
#'
#' Creates a large number of life tables simulated from different latent factor paths
#' and averages them to create 1 life table output.
#'
#' @param init_age
#' integer between 65 and 110 denoting initial age of individual
#' @param female
#' 1 for female, 0 for male
#' @param year
#' integer denoting year of individual
#' @param param_file
#' file containing parameters of cox regression model
#' @param init_state
#' 0 for healthy, 1 for disabled
#' @param n_sim
#' number of latent factor paths to simulate
#' @param cohort
#' cohort size of lifetable
#' @param mean
#' FALSE to return list of lifetables, TRUE to return expected lifetable
#'
#' @return
#' Dataframe containing life table
#'
#'
#' @examples example
health3_simulate_life_table <- function(init_age, female, year, param_file, init_state, n_sim, cohort, mean) {
    # flagging errors
    if (as.integer(n_sim) != n_sim) {
    stop('n_sim must be an integer')
    }

    if (n_sim <= 0) {
    stop('n_sim must be a positive integer')
    }

    if (init_age < 65 | init_age > 110) {
    stop('invalid age')
    }

    if (as.integer(init_age) != init_age) {
    stop('initial age must be an integer')
    }

    if (init_state != 0 & init_state != 1) {
    stop('invalid state, enter 0 for healthy, 1 for disabled')
    }

    if (cohort != floor(cohort)) {
    stop('cohort must be integer value')
    }

    if (cohort <= 0) {
    stop('cohort must be positive integer')
    }

    life_tables <- list()
    for (i in 1:n_sim) {
    TP <- health3_get_trans_probs('F', param_file, init_age, female, year)
    LT <- health3_create_life_table(TP, init_age, init_state, cohort)
    life_tables[[i]] <- LT
    }

    if (mean == TRUE) {
    return(Reduce('+', life_tables)/n_sim)
    } else {
    return(life_tables)
    }

}






